group "30 external"
include "scripts/premake/external/taskflow.lua"
include "scripts/premake/external/imgui.lua"
include "scripts/premake/external/entt.lua"
include "scripts/premake/external/tracy.lua"
include "scripts/premake/external/glfw.lua"
include "scripts/premake/external/vulkan.lua"
include "scripts/premake/external/qt.lua"
