group "30 external"
include "scripts/premake/external/taskflow.lua"
include "scripts/premake/external/imgui.lua"
include "scripts/premake/external/entt.lua"
include "scripts/premake/external/tracy.lua"